# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optimizers_pyqt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 651)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plot_widget = QtWidgets.QWidget(self.centralwidget)
        self.plot_widget.setGeometry(QtCore.QRect(0, 0, 441, 471))
        self.plot_widget.setObjectName("plot_widget")
        self.step_label = QtWidgets.QLabel(self.plot_widget)
        self.step_label.setGeometry(QtCore.QRect(330, 0, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.step_label.setFont(font)
        self.step_label.setText("")
        self.step_label.setObjectName("step_label")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(630, 570, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.three_dims_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.three_dims_checkbox.setGeometry(QtCore.QRect(10, 480, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.three_dims_checkbox.setFont(font)
        self.three_dims_checkbox.setObjectName("three_dims_checkbox")
        self.animation_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.animation_checkbox.setGeometry(QtCore.QRect(10, 510, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.animation_checkbox.setFont(font)
        self.animation_checkbox.setObjectName("animation_checkbox")
        self.initial_x_textedit = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_x_textedit.setGeometry(QtCore.QRect(140, 480, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.initial_x_textedit.setFont(font)
        self.initial_x_textedit.setObjectName("initial_x_textedit")
        self.initial_y_textedit = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_y_textedit.setGeometry(QtCore.QRect(140, 510, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.initial_y_textedit.setFont(font)
        self.initial_y_textedit.setObjectName("initial_y_textedit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 480, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 510, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.steps_textedit = QtWidgets.QLineEdit(self.centralwidget)
        self.steps_textedit.setGeometry(QtCore.QRect(300, 480, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.steps_textedit.setFont(font)
        self.steps_textedit.setObjectName("steps_textedit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 480, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.reset_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.reset_checkbox.setEnabled(True)
        self.reset_checkbox.setGeometry(QtCore.QRect(570, 570, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.reset_checkbox.setFont(font)
        self.reset_checkbox.setChecked(True)
        self.reset_checkbox.setObjectName("reset_checkbox")
        self.optimizers_listview = QtWidgets.QListWidget(self.centralwidget)
        self.optimizers_listview.setGeometry(QtCore.QRect(460, 10, 291, 461))
        self.optimizers_listview.setAutoFillBackground(True)
        self.optimizers_listview.setLineWidth(0)
        self.optimizers_listview.setAutoScroll(False)
        self.optimizers_listview.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.optimizers_listview.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.optimizers_listview.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.optimizers_listview.setMovement(QtWidgets.QListView.Static)
        self.optimizers_listview.setObjectName("optimizers_listview")
        self.function_textedit = QtWidgets.QLineEdit(self.centralwidget)
        self.function_textedit.setGeometry(QtCore.QRect(10, 540, 360, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.function_textedit.setFont(font)
        self.function_textedit.setText("")
        self.function_textedit.setObjectName("function_textedit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 540, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(460, 480, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.remove_button.setFont(font)
        self.remove_button.setObjectName("remove_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(650, 480, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.animation_trigger_button = QtWidgets.QPushButton(self.centralwidget)
        self.animation_trigger_button.setGeometry(QtCore.QRect(460, 570, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.animation_trigger_button.setFont(font)
        self.animation_trigger_button.setObjectName("animation_trigger_button")
        self.function_check_button = QtWidgets.QPushButton(self.centralwidget)
        self.function_check_button.setGeometry(QtCore.QRect(630, 540, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.function_check_button.setFont(font)
        self.function_check_button.setObjectName("function_check_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.functions_menu = QtWidgets.QMenu(self.menubar)
        self.functions_menu.setObjectName("functions_menu")
        self.add_menu = QtWidgets.QMenu(self.menubar)
        self.add_menu.setObjectName("add_menu")
        self.info_menu = QtWidgets.QMenu(self.menubar)
        self.info_menu.setObjectName("info_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.plot_range = QtWidgets.QAction(MainWindow)
        self.plot_range.setObjectName("plot_range")
        self.plot_type = QtWidgets.QAction(MainWindow)
        self.plot_type.setObjectName("plot_type")
        self.plot_cmap = QtWidgets.QAction(MainWindow)
        self.plot_cmap.setObjectName("plot_cmap")
        self.plot_optims = QtWidgets.QAction(MainWindow)
        self.plot_optims.setObjectName("plot_optims")
        self.new_optimizer = QtWidgets.QAction(MainWindow)
        self.new_optimizer.setObjectName("new_optimizer")
        self.base_optimizer = QtWidgets.QAction(MainWindow)
        self.base_optimizer.setObjectName("base_optimizer")
        self.example_optimizer = QtWidgets.QAction(MainWindow)
        self.example_optimizer.setObjectName("example_optimizer")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.menu.addAction(self.plot_range)
        self.menu.addAction(self.plot_type)
        self.menu.addAction(self.plot_cmap)
        self.menu.addAction(self.plot_optims)
        self.add_menu.addAction(self.new_optimizer)
        self.add_menu.addAction(self.base_optimizer)
        self.add_menu.addAction(self.example_optimizer)
        self.info_menu.addAction(self.about)
        self.menubar.addAction(self.add_menu.menuAction())
        self.menubar.addAction(self.functions_menu.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.info_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Optimizers"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.three_dims_checkbox.setText(_translate("MainWindow", "3D"))
        self.animation_checkbox.setText(_translate("MainWindow", "Animation"))
        self.initial_x_textedit.setText(_translate("MainWindow", "0"))
        self.initial_y_textedit.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Initial X"))
        self.label_2.setText(_translate("MainWindow", "Initial Y"))
        self.steps_textedit.setText(_translate("MainWindow", "100"))
        self.label_3.setText(_translate("MainWindow", "Steps"))
        self.reset_checkbox.setText(_translate("MainWindow", "Reset"))
        self.label_4.setText(_translate("MainWindow", "Function"))
        self.remove_button.setText(_translate("MainWindow", "Remove"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.animation_trigger_button.setText(_translate("MainWindow", "Pause"))
        self.function_check_button.setText(_translate("MainWindow", "Function Check"))
        self.menu.setTitle(_translate("MainWindow", "Настройки"))
        self.functions_menu.setTitle(_translate("MainWindow", "Функции"))
        self.add_menu.setTitle(_translate("MainWindow", "Файл"))
        self.info_menu.setTitle(_translate("MainWindow", "Информация"))
        self.plot_range.setText(_translate("MainWindow", "Диапазон графика"))
        self.plot_type.setText(_translate("MainWindow", "Тип графика"))
        self.plot_cmap.setText(_translate("MainWindow", "Цветовая схема графика"))
        self.plot_optims.setText(_translate("MainWindow", "Цвета оптимизаторов"))
        self.new_optimizer.setText(_translate("MainWindow", "Добавить новый оптимизатор"))
        self.base_optimizer.setText(_translate("MainWindow", "Сохранить базовый оптимизатор"))
        self.example_optimizer.setText(_translate("MainWindow", "Сохранить пример оптимизатора"))
        self.about.setText(_translate("MainWindow", "О программе"))

