# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'optimizers_pyqt_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QLabel,
    QLineEdit, QListView, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(767, 651)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.plot_range = QAction(MainWindow)
        self.plot_range.setObjectName(u"plot_range")
        self.plot_type = QAction(MainWindow)
        self.plot_type.setObjectName(u"plot_type")
        self.plot_cmap = QAction(MainWindow)
        self.plot_cmap.setObjectName(u"plot_cmap")
        self.plot_optims = QAction(MainWindow)
        self.plot_optims.setObjectName(u"plot_optims")
        self.new_optimizer = QAction(MainWindow)
        self.new_optimizer.setObjectName(u"new_optimizer")
        self.base_optimizer = QAction(MainWindow)
        self.base_optimizer.setObjectName(u"base_optimizer")
        self.example_optimizer = QAction(MainWindow)
        self.example_optimizer.setObjectName(u"example_optimizer")
        self.about = QAction(MainWindow)
        self.about.setObjectName(u"about")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.plot_widget = QWidget(self.centralwidget)
        self.plot_widget.setObjectName(u"plot_widget")
        self.plot_widget.setGeometry(QRect(0, 0, 441, 471))
        self.step_label = QLabel(self.plot_widget)
        self.step_label.setObjectName(u"step_label")
        self.step_label.setGeometry(QRect(330, 0, 101, 21))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.step_label.setFont(font)
        self.start_button = QPushButton(self.centralwidget)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(630, 570, 120, 30))
        font1 = QFont()
        font1.setPointSize(12)
        self.start_button.setFont(font1)
        self.three_dims_checkbox = QCheckBox(self.centralwidget)
        self.three_dims_checkbox.setObjectName(u"three_dims_checkbox")
        self.three_dims_checkbox.setGeometry(QRect(10, 480, 80, 25))
        self.three_dims_checkbox.setFont(font1)
        self.animation_checkbox = QCheckBox(self.centralwidget)
        self.animation_checkbox.setObjectName(u"animation_checkbox")
        self.animation_checkbox.setGeometry(QRect(10, 510, 80, 25))
        self.animation_checkbox.setFont(font1)
        self.animation_checkbox.setChecked(True)
        self.initial_x_textedit = QLineEdit(self.centralwidget)
        self.initial_x_textedit.setObjectName(u"initial_x_textedit")
        self.initial_x_textedit.setGeometry(QRect(140, 480, 70, 25))
        self.initial_x_textedit.setFont(font1)
        self.initial_y_textedit = QLineEdit(self.centralwidget)
        self.initial_y_textedit.setObjectName(u"initial_y_textedit")
        self.initial_y_textedit.setGeometry(QRect(140, 510, 70, 25))
        self.initial_y_textedit.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 480, 50, 25))
        self.label.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(220, 510, 50, 25))
        self.label_2.setFont(font1)
        self.steps_textedit = QLineEdit(self.centralwidget)
        self.steps_textedit.setObjectName(u"steps_textedit")
        self.steps_textedit.setGeometry(QRect(300, 480, 70, 25))
        self.steps_textedit.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(380, 480, 60, 25))
        self.label_3.setFont(font1)
        self.tail_textedit = QLineEdit(self.centralwidget)
        self.tail_textedit.setObjectName(u"tail_textedit")
        self.tail_textedit.setGeometry(QRect(300, 540, 70, 25))
        self.tail_textedit.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(380, 540, 60, 25))
        self.label_5.setFont(font1)
        self.speed_slider = QSlider(self.centralwidget)
        self.speed_slider.setObjectName(u"speed_slider")
        self.speed_slider.setGeometry(QRect(300, 510, 70, 25))
        self.speed_slider.setMinimum(-3)
        self.speed_slider.setMaximum(6)
        self.speed_slider.setPageStep(1)
        self.speed_slider.setValue(0)
        self.speed_slider.setOrientation(Qt.Orientation.Horizontal)
        self.speed_label = QLabel(self.centralwidget)
        self.speed_label.setObjectName(u"speed_label")
        self.speed_label.setGeometry(QRect(380, 510, 90, 25))
        self.speed_label.setFont(font1)
        self.reset_checkbox = QCheckBox(self.centralwidget)
        self.reset_checkbox.setObjectName(u"reset_checkbox")
        self.reset_checkbox.setEnabled(True)
        self.reset_checkbox.setGeometry(QRect(570, 570, 60, 30))
        self.reset_checkbox.setFont(font1)
        self.reset_checkbox.setChecked(True)
        self.optimizers_listview = QListWidget(self.centralwidget)
        self.optimizers_listview.setObjectName(u"optimizers_listview")
        self.optimizers_listview.setGeometry(QRect(460, 10, 291, 461))
        self.optimizers_listview.setAutoFillBackground(True)
        self.optimizers_listview.setLineWidth(0)
        self.optimizers_listview.setAutoScroll(False)
        self.optimizers_listview.setDragDropMode(QAbstractItemView.NoDragDrop)
        self.optimizers_listview.setDefaultDropAction(Qt.IgnoreAction)
        self.optimizers_listview.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.optimizers_listview.setMovement(QListView.Static)
        self.function_textedit = QLineEdit(self.centralwidget)
        self.function_textedit.setObjectName(u"function_textedit")
        self.function_textedit.setGeometry(QRect(10, 540, 360, 25))
        self.function_textedit.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(380, 540, 60, 25))
        self.label_4.setFont(font1)
        self.remove_button = QPushButton(self.centralwidget)
        self.remove_button.setObjectName(u"remove_button")
        self.remove_button.setGeometry(QRect(460, 480, 100, 25))
        self.remove_button.setFont(font1)
        self.add_button = QPushButton(self.centralwidget)
        self.add_button.setObjectName(u"add_button")
        self.add_button.setGeometry(QRect(650, 480, 100, 25))
        self.add_button.setFont(font1)
        self.animation_trigger_button = QPushButton(self.centralwidget)
        self.animation_trigger_button.setObjectName(u"animation_trigger_button")
        self.animation_trigger_button.setGeometry(QRect(460, 570, 100, 30))
        self.animation_trigger_button.setFont(font1)
        self.function_check_button = QPushButton(self.centralwidget)
        self.function_check_button.setObjectName(u"function_check_button")
        self.function_check_button.setGeometry(QRect(630, 540, 121, 25))
        self.function_check_button.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 767, 21))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.functions_menu = QMenu(self.menubar)
        self.functions_menu.setObjectName(u"functions_menu")
        self.add_menu = QMenu(self.menubar)
        self.add_menu.setObjectName(u"add_menu")
        self.info_menu = QMenu(self.menubar)
        self.info_menu.setObjectName(u"info_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.add_menu.menuAction())
        self.menubar.addAction(self.functions_menu.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.info_menu.menuAction())
        self.menu.addAction(self.plot_range)
        self.menu.addAction(self.plot_type)
        self.menu.addAction(self.plot_cmap)
        self.menu.addAction(self.plot_optims)
        self.add_menu.addAction(self.new_optimizer)
        self.add_menu.addAction(self.base_optimizer)
        self.add_menu.addAction(self.example_optimizer)
        self.info_menu.addAction(self.about)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Optimizers", None))
        self.plot_range.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0438\u0430\u043f\u0430\u0437\u043e\u043d \u0433\u0440\u0430\u0444\u0438\u043a\u0430", None))
        self.plot_type.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0438\u043f \u0433\u0440\u0430\u0444\u0438\u043a\u0430", None))
        self.plot_cmap.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0432\u0435\u0442\u043e\u0432\u0430\u044f \u0441\u0445\u0435\u043c\u0430 \u0433\u0440\u0430\u0444\u0438\u043a\u0430", None))
        self.plot_optims.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0432\u0435\u0442\u0430 \u043e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440\u043e\u0432", None))
        self.new_optimizer.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043d\u043e\u0432\u044b\u0439 \u043e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440", None))
        self.base_optimizer.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0431\u0430\u0437\u043e\u0432\u044b\u0439 \u043e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440", None))
        self.example_optimizer.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u0440 \u043e\u043f\u0442\u0438\u043c\u0438\u0437\u0430\u0442\u043e\u0440\u0430", None))
        self.about.setText(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
        self.step_label.setText("")
        self.start_button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.three_dims_checkbox.setText(QCoreApplication.translate("MainWindow", u"3D", None))
        self.animation_checkbox.setText(QCoreApplication.translate("MainWindow", u"Animation", None))
        self.initial_x_textedit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.initial_y_textedit.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Initial X", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Initial Y", None))
        self.steps_textedit.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Steps", None))
        self.tail_textedit.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Tail", None))
        self.speed_label.setText(QCoreApplication.translate("MainWindow", u"Speed \u00d71", None))
        self.reset_checkbox.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.function_textedit.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Function", None))
        self.remove_button.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.add_button.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.animation_trigger_button.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.function_check_button.setText(QCoreApplication.translate("MainWindow", u"Function Check", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438", None))
        self.functions_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u0424\u0443\u043d\u043a\u0446\u0438\u0438", None))
        self.add_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u0424\u0430\u0439\u043b", None))
        self.info_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f", None))
    # retranslateUi

