# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_range_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 200)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 60, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.to_x_edit = QtWidgets.QLineEdit(Dialog)
        self.to_x_edit.setGeometry(QtCore.QRect(60, 60, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.to_x_edit.setFont(font)
        self.to_x_edit.setObjectName("to_x_edit")
        self.from_x_edit = QtWidgets.QLineEdit(Dialog)
        self.from_x_edit.setGeometry(QtCore.QRect(60, 30, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.from_x_edit.setFont(font)
        self.from_x_edit.setObjectName("from_x_edit")
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setGeometry(QtCore.QRect(170, 160, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ok_button.setFont(font)
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(80, 160, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.count_edit = QtWidgets.QLineEdit(Dialog)
        self.count_edit.setGeometry(QtCore.QRect(170, 120, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.count_edit.setFont(font)
        self.count_edit.setObjectName("count_edit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.xy_checkbox = QtWidgets.QCheckBox(Dialog)
        self.xy_checkbox.setGeometry(QtCore.QRect(10, 90, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xy_checkbox.setFont(font)
        self.xy_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xy_checkbox.setObjectName("xy_checkbox")
        self.from_y_edit = QtWidgets.QLineEdit(Dialog)
        self.from_y_edit.setGeometry(QtCore.QRect(170, 30, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.from_y_edit.setFont(font)
        self.from_y_edit.setObjectName("from_y_edit")
        self.to_y_edit = QtWidgets.QLineEdit(Dialog)
        self.to_y_edit.setGeometry(QtCore.QRect(170, 60, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.to_y_edit.setFont(font)
        self.to_y_edit.setObjectName("to_y_edit")
        self.x_label = QtWidgets.QLabel(Dialog)
        self.x_label.setGeometry(QtCore.QRect(90, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(Dialog)
        self.y_label.setGeometry(QtCore.QRect(200, 10, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Диапазон"))
        self.label.setText(_translate("Dialog", "До"))
        self.label_2.setText(_translate("Dialog", "От"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.label_3.setText(_translate("Dialog", "Количество точек"))
        self.xy_checkbox.setText(_translate("Dialog", "Отдельно X и Y"))
        self.x_label.setText(_translate("Dialog", "X"))
        self.y_label.setText(_translate("Dialog", "Y"))

